clc;clear all;
fm1=input('Enter max freq of sine1: ');
fm2=input('Enter max freq of sine2: ');
fs=input('Enter sampling freq: ');
w1=(2*pi*fm1)/fs;
w2=(2*pi*fm2)/fs;
N=1024;
k=0:N-1;
n=0:N-1;
x1 = sin(w1*n);
x2 = sin(w2*n);
X = DiscreteFTFn(x1,N,k,n);
X1=abs(X);
X2=X1(1:N/2);
Y = DiscreteFTFn(x2,N,k,n);
Y1 = abs(Y);
Y2=Y1(1:N/2);
f=(fs/2)*linspace(0,1,N/2);
x3=x1+x2;
X3=DiscreteFTFn(x3,N,k,n);
Z=abs(X3);
Z1=Z(1:N/2);
subplot(2,2,1);stem(f,X2);title('DFT of Sine1');xlabel('f');ylabel('abs(X1)');
subplot(2,2,2);stem(f,Y2);title('DFT of Sine2');xlabel('f');ylabel('abs(X2)');
subplot(2,2,3);stem(f,Z1);title('DFT of Sine1+Sine2');xlabel('f');ylabel('abs(Z)');
subplot(2,2,4);stem(f,(Z1.^2));title('Power Spectrum of Sum');xlabel('f');ylabel('abs(Z^2)');