clc;clear all;
fm = input('Enter max freq of sine: ');
fs = input('Enter sampling freq: ');
i= input('Enter interpolation factor: ');
w = (2*pi*fm)/fs;
n = 1:100;
x = sin(w*n);
n1 = linspace(1,100,i*length(n));
y = zeros(1,length(n1));
y(1:i:end) = x;
y1 = upsample(x,i);
y2 = interp(x,i);
[b,a] = butter(2,fm/(fs),'low');
y3 = filter(b,a,y);
subplot(3,2,1);stem(n,x);title('Original signal');xlabel('n');
subplot(3,2,2);stem(n1,y);title('After interpolation');xlabel('n');
subplot(3,2,3);stem(n1,y1);title('upsample()');xlabel('n');
subplot(3,2,4);stem(n1,y2);title('interp()');xlabel('n');
subplot(3,2,5);stem(n1,y3);title('After interpolation & filter');xlabel('n');